// Copyright (C) 2026 protonctx contributors
// SPDX-License-Identifier: GPL-3.0-only

import { Button, HorizontalBox, VerticalBox } from "std-widgets.slint";

// About dialog with version info.
export component AboutDialog inherits Dialog {
    title: "About protonctx";
    icon: @image-url("icon/icon.svg");
    in property <string> about-text: "";
    preferred-width: 380px;
    preferred-height: 200px;
    min-width: 380px;
    min-height: 200px;

    VerticalBox {
        padding: 16px;
        Text {
            text: root.about-text;
            wrap: word-wrap;
        }
        HorizontalBox {
            alignment: end;
            Button {
                text: "Close";
                clicked => {
                    root.hide();
                }
            }
        }
    }
}